### ISSUE TITLE
Error in images of loots

### ISSUE THREAD

**Issue by allstar1992** [EgzoT/-OTClient-Mod-loot_stats#4]
I have the error that some items do not appear, and in some cases some items appear and in others not, such as ham. I was with the same mistake with the gold coin but I corrected with the plural, but in others it did not work, I ask you to post the items xml you use to make a comparison.
Please Help me.
(terminal of otclient shows the items xml read successfully)
![erro](https://user-images.githubusercontent.com/53419307/62022924-d05cb400-b1a4-11e9-926c-9191ddde637b.png)

**Comment by EgzoT** [comment]
.xml file may load successful but it may be incomplete.
The best way is download .xml from OT servers who was created for production.

![imageLoot](https://dl.getdropbox.com/s/wo5l3p2mg4uxr76/20190729172914_1.png)

**Comment by allstar1992** [comment]
My loot show on server log, not in default, and my last loot no have point in the end, this may cause errors?

**Comment by EgzoT** [comment]
Give me your server name and I will test that.

**Comment by allstar1992** [comment]
https://tibiaking.com/forums/topic/93859-telara-ats/ 
I used protocol min 10.98 and protocol max 11.57, tested loot stats with 10.98 otclient last version)
(attachment with executable compiled for windows x64)

[theforgottenserver.zip](https://github.com/EgzoT/-OTClient-Mod-loot_stats/files/3447741/theforgottenserver.zip)

**Comment by EgzoT** [comment]
Fix: 579ec37
Bug with lost last letter in last word in loot log was fixed.
Probably now it will work.

Download and check that is all working, then close this issue (if all will work fine).

**Comment by allstar1992** [comment]
i tested and work fine, thank you very much for the support.
